# Generated by Django 5.0.1 on 2024-04-08 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports_app", "0002_initial"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointment_id",
                    models.CharField(
                        max_length=25, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, default=None, null=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[("Physical", "Physical"), ("Online", "Online")],
                        max_length=10,
                    ),
                ),
                ("student_full_name", models.CharField(max_length=100)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_phone", models.CharField(max_length=15)),
                ("student_reg_no", models.CharField(max_length=20)),
                ("student_gender", models.CharField(max_length=6)),
                ("consultant_phone", models.CharField(max_length=15)),
                ("consultant_office", models.CharField(max_length=20)),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="scheduled_appointments",
                        to="users_app.consultant",
                    ),
                ),
                (
                    "report_id",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="reports_app.report",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="scheduled_appointments",
                        to="users_app.student",
                    ),
                ),
            ],
        ),
    ]
