# Generated by Django 5.0.1 on 2024-05-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments_app", "0001_initial"),
        ("reports_app", "0001_initial"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="appointments_created",
                to="users_app.student",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="consultant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="scheduled_appointments",
                to="users_app.consultant",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="report_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="reports_app.report",
            ),
        ),
    ]
