# Generated by Django 5.0.1 on 2024-05-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="physical_location",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
