# Generated by Django 5.0.1 on 2024-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_app", "0003_alter_appointment_physical_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="physical_location",
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
