# Generated by Django 5.0.1 on 2024-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_app", "0004_alter_appointment_physical_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "REQUESTED"),
                    ("SCHEDULED", "SCHEDULED"),
                    ("CLOSED", "CLOSED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="REQUESTED",
                max_length=15,
            ),
        ),
    ]
