# Generated by Django 5.0.1 on 2024-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_app", "0005_alter_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "REQUESTED"),
                    ("SCHEDULED", "SCHEDULED"),
                    ("CLOSED", "CLOSED"),
                    ("CANCELLED", "CANCELLED"),
                    ("MISSED", "MISSED"),
                ],
                default="REQUESTED",
                max_length=15,
            ),
        ),
    ]
