# Generated by Django 5.0.1 on 2024-07-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_app", "0006_alter_appointment_date_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="meeting_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
