# Generated by Django 5.0.1 on 2024-07-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_app", "0007_appointment_meeting_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="meeting_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
