# Generated by Django 5.0.1 on 2024-05-05 18:39

import reports_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnonymousEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assets/evidence/",
                        validators=[reports_app.models.validate_file_size],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnonymousReport",
            fields=[
                (
                    "report_id",
                    models.CharField(
                        max_length=25, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "abuse_type",
                    models.CharField(
                        choices=[
                            ("Physical Violence", "Physical Violence"),
                            ("Sexual Violence", "Sexual Violence"),
                            ("Psychological Violence", "Psychological Violence"),
                            ("Online Harassment", "Online Harassment"),
                            ("Societal Violence", "Societal Violence"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_and_time", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Hall I", "Hall I"),
                            ("Hall II", "Hall II"),
                            ("Hall III", "Hall III"),
                            ("Hall IV", "Hall IV"),
                            ("Hall V", "Hall V"),
                            ("Hall VI", "Hall VI"),
                            ("Hall VII", "Hall VII"),
                            ("Magufuli Hostels", "Magufuli Hostels"),
                            ("Mabibo Hostels", "Mabibo Hostels"),
                            ("Kunduchi Hostels", "Kunduchi Hostels"),
                            ("CoICT Hostels", "CoICT Hostels"),
                            ("Ubungo Hostels", "Ubungo Hostels"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "other_location",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "perpetrator_fullname",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("perpetrator_gender", models.TextField(max_length=20)),
                ("relationship", models.TextField(max_length=20)),
                (
                    "police_status",
                    models.CharField(default="UNFORWARDED", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="assets/evidence/",
                        validators=[reports_app.models.validate_file_size],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "report_for",
                    models.CharField(
                        choices=[("Self", "Self"), ("Else", "Else")], max_length=10
                    ),
                ),
                (
                    "report_id",
                    models.CharField(
                        max_length=25, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("reporter_full_name", models.CharField(max_length=255)),
                ("reporter_gender", models.CharField(max_length=6)),
                ("reporter_college", models.CharField(max_length=255)),
                ("reporter_reg_no", models.CharField(max_length=255)),
                ("reporter_email", models.EmailField(max_length=254)),
                ("reporter_phone", models.CharField(max_length=20)),
                ("victim_email", models.EmailField(max_length=254)),
                ("victim_full_name", models.CharField(max_length=255)),
                ("victim_phone", models.CharField(max_length=20)),
                ("victim_gender", models.CharField(max_length=20)),
                ("victim_reg_no", models.CharField(max_length=255)),
                ("victim_college", models.CharField(max_length=255)),
                (
                    "abuse_type",
                    models.CharField(
                        choices=[
                            ("Physical Violence", "Physical Violence"),
                            ("Sexual Violence", "Sexual Violence"),
                            ("Psychological Violence", "Psychological Violence"),
                            ("Online Harassment", "Online Harassment"),
                            ("Societal Violence", "Societal Violence"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date_and_time", models.DateTimeField()),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("Hall I", "Hall I"),
                            ("Hall II", "Hall II"),
                            ("Hall III", "Hall III"),
                            ("Hall IV", "Hall IV"),
                            ("Hall V", "Hall V"),
                            ("Hall VI", "Hall VI"),
                            ("Hall VII", "Hall VII"),
                            ("Magufuli Hostels", "Magufuli Hostels"),
                            ("Mabibo Hostels", "Mabibo Hostels"),
                            ("Kunduchi Hostels", "Kunduchi Hostels"),
                            ("CoICT Hostels", "CoICT Hostels"),
                            ("Ubungo Hostels", "Ubungo Hostels"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "other_location",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "perpetrator_fullname",
                    models.TextField(blank=True, max_length=20, null=True),
                ),
                ("perpetrator_gender", models.TextField(max_length=20)),
                ("relationship", models.TextField(max_length=50)),
                (
                    "police_status",
                    models.CharField(default="UNFORWARDED", max_length=20),
                ),
            ],
        ),
    ]
