# Generated by Django 5.0.1 on 2024-05-05 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports_app", "0001_initial"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousreport",
            name="assigned_gd",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.genderdesk",
            ),
        ),
        migrations.AddField(
            model_name="anonymousreport",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.police",
            ),
        ),
        migrations.AddField(
            model_name="anonymousevidence",
            name="report",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anonymous_evidence",
                to="reports_app.anonymousreport",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="assigned_gd",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.genderdesk",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.police",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_cases",
                to="users_app.student",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="report",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_evidence",
                to="reports_app.report",
            ),
        ),
    ]
