# Generated by Django 5.0.1 on 2024-03-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
