# Generated by Django 5.0.1 on 2024-06-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0003_alter_anonymousevidence_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousreport",
            name="reporter_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
