# Generated by Django 5.0.1 on 2024-04-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0003_remove_report_evidence_anonymousreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymousreport",
            name="other_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="anonymousreport",
            name="rejection_reason",
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="other_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="anonymousreport",
            name="location",
            field=models.CharField(
                choices=[
                    ("Hall I", "Hall I"),
                    ("Hall II", "Hall II"),
                    ("Hall III", "Hall III"),
                    ("Hall IV", "Hall IV"),
                    ("Hall V", "Hall V"),
                    ("Hall VI", "Hall VI"),
                    ("Hall VII", "Hall VII"),
                    ("Magufuli Hostels", "Magufuli Hostels"),
                    ("Mabibo Hostels", "Mabibo Hostels"),
                    ("Kunduchi Hostels", "Kunduchi Hostels"),
                    ("CoICT Hostels", "CoICT Hostels"),
                    ("Ubungo Hostels", "Ubungo Hostels"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="anonymousreport",
            name="perpetrator_fullname",
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="report",
            name="location",
            field=models.CharField(
                choices=[
                    ("Hall I", "Hall I"),
                    ("Hall II", "Hall II"),
                    ("Hall III", "Hall III"),
                    ("Hall IV", "Hall IV"),
                    ("Hall V", "Hall V"),
                    ("Hall VI", "Hall VI"),
                    ("Hall VII", "Hall VII"),
                    ("Magufuli Hostels", "Magufuli Hostels"),
                    ("Mabibo Hostels", "Mabibo Hostels"),
                    ("Kunduchi Hostels", "Kunduchi Hostels"),
                    ("CoICT Hostels", "CoICT Hostels"),
                    ("Ubungo Hostels", "Ubungo Hostels"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="perpetrator_fullname",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="relationship",
            field=models.TextField(max_length=50),
        ),
    ]
