# Generated by Django 5.0.1 on 2024-06-30 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0004_anonymousreport_reporter_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anonymousreport",
            name="reporter_phone",
        ),
    ]
