# Generated by Django 5.0.1 on 2024-04-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0004_anonymousreport_other_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousreport",
            name="perpetrator_fullname",
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
