# Generated by Django 5.0.1 on 2024-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0005_alter_anonymousreport_perpetrator_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousreport",
            name="abuse_type",
            field=models.CharField(
                choices=[
                    ("Physical Violence", "Physical Violence"),
                    ("Sexual Violence", "Sexual Violence"),
                    ("Psychological Violence", "Psychological Violence"),
                    ("Online Harassment", "Online Harassment"),
                    ("Societal Violence", "Societal Violence"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="abuse_type",
            field=models.CharField(
                choices=[
                    ("Physical Violence", "Physical Violence"),
                    ("Sexual Violence", "Sexual Violence"),
                    ("Psychological Violence", "Psychological Violence"),
                    ("Online Harassment", "Online Harassment"),
                    ("Societal Violence", "Societal Violence"),
                ],
                max_length=50,
            ),
        ),
    ]
