# Generated by Django 5.0.1 on 2024-05-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0006_alter_anonymousreport_abuse_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="victim_gender",
            field=models.CharField(max_length=20),
        ),
    ]
