# Generated by Django 5.0.1 on 2024-05-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0007_alter_report_victim_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousreport",
            name="other_location",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="other_location",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
