# Generated by Django 5.0.1 on 2024-05-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0008_alter_anonymousreport_other_location_and_more"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousreport",
            name="assigned_gd",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.genderdesk",
            ),
        ),
        migrations.AlterField(
            model_name="anonymousreport",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.police",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="assigned_gd",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.genderdesk",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.police",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_cases",
                to="users_app.student",
            ),
        ),
    ]
