# Generated by Django 5.0.1 on 2024-05-02 20:50

import reports_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_app", "0009_alter_anonymousreport_assigned_gd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anonymousevidence",
            name="evidence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assets/evidence/",
                validators=[reports_app.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="evidence",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assets/evidence/",
                validators=[reports_app.models.validate_file_size],
            ),
        ),
    ]
