# Generated by Django 5.0.1 on 2024-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="police",
            name="station",
            field=models.CharField(max_length=25),
        ),
    ]
